from __future__ import annotations

import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
STRUCTURED_DIR = ROOT / "materials" / "exam-papers" / "structured"


def sub(question_id: str, label: str, prompt: str, score: float | None = None, answer_type: str = "text", options: list[dict[str, str]] | None = None) -> dict[str, Any]:
    return {
        "id": question_id,
        "label": label,
        "prompt": prompt,
        "score": score,
        "answer_type": answer_type,
        "options": options or [],
    }


def question(
    *,
    qid: str,
    section_id: str,
    number: str,
    title: str,
    score: float,
    stem: str,
    prompts: list[tuple[str, str, float | None]],
) -> dict[str, Any]:
    return {
        "id": qid,
        "section_id": section_id,
        "number": number,
        "title": title,
        "score": score,
        "stem": stem,
        "sub_questions": [
            sub(f"{qid}-{index}", label, prompt, item_score)
            for index, (label, prompt, item_score) in enumerate(prompts, start=1)
        ],
    }


def choice_group(qid: str, section_id: str, number: str, title: str, score: float, items: list[tuple[str, str, list[tuple[str, str]]]]) -> dict[str, Any]:
    return {
        "id": qid,
        "section_id": section_id,
        "number": number,
        "title": title,
        "score": score,
        "stem": "单选题。",
        "sub_questions": [
            sub(
                f"{qid}-{index}",
                label,
                prompt,
                1,
                "single_choice",
                [{"key": key, "text": text} for key, text in options],
            )
            for index, (label, prompt, options) in enumerate(items, start=1)
        ],
    }


DATA: dict[int, list[dict[str, Any]]] = {
    2022: [
        question(
            qid="analysis-1",
            section_id="analysis",
            number="一、1",
            title="C 程序片段与 32 位补码比较",
            score=4,
            stem="某 32 位模型计算机上，有 C 语言程序片段：\nint i,a[10],b[10];\nfor (i=0;i<=10;i++)\n    if (b[i]<a[i]) b[i]=a[i]+20;\n\n假设初始 a[5]=0x7FFFFFFF，b[5]=0xFFFFFFFF。",
            prompts=[("作答", "执行完上述 for 循环语句后，b[5] 的结果是多少？请以 16 进制表示，写出推导或计算过程。", 4)],
        ),
        question(
            qid="analysis-2",
            section_id="analysis",
            number="一、2",
            title="b[5]-a[5] 与标志位",
            score=4,
            stem="if (b[i]<a[i]) 这条判断语句，在计算机中是通过 b[i]-a[i] 来实现的。",
            prompts=[("作答", "执行 b[5]-a[5] 后，标志位 CF、OF、ZF、SF 的值是多少？", 4)],
        ),
        question(
            qid="analysis-3",
            section_id="analysis",
            number="一、3",
            title="16 位自定义浮点数编码与加法",
            score=7,
            stem="假设数组 a 和 b 的数据类型是一种 16 位长的自定义浮点数：高 6 位是含阶符在内的阶码，低 10 位是含数符在内的尾数，尾数和阶码都由补码表示。若 a[0] = -15.25，b[0] = 5/32。",
            prompts=[
                ("1）", "请写出 a[0] 和 b[0] 在内存中的规格化浮点数编码（以 16 进制表示）。", 2),
                ("2）", "计算 a[0]+b[0] 的浮点数 [a[0]+b[0]]浮（采用 0 舍 1 入法，结果以 16 进制表示，列出计算步骤）。", 5),
            ],
        ),
        question(
            qid="memory-1",
            section_id="memory",
            number="二、1",
            title="2M 主存空间 SRAM 连接设计",
            score=14,
            stem="假设某 8 位模型计算机的地址总线为 24 位，存储器按字节编址，CPU 有 M/IO（=0 访问 I/O 设备，=1 访问主存）、R/W（=0 写操作，=1 读操作）信号。从地址 100000H 开始，设计一个 2M 空间的主存储器。可使用若干 1M×4 位 SRAM 芯片、一个 2:4 译码器芯片（带低电平使能端，译码输出为低电平）、与非门和或非门。",
            prompts=[("作答", "请分析所需芯片个数、2M 空间的地址范围，并画出与 CPU 的连接图。", 14)],
        ),
        question(
            qid="memory-2",
            section_id="memory",
            number="二、2",
            title="4KB 8 路组相联指令 Cache",
            score=9,
            stem="为该 8 位模型计算机配备一个 4KB 的 8 路组相联指令 Cache，每行 16 个字。",
            prompts=[
                ("1）", "请写出对主存地址字段的划分（包括各字段的名称及位数）。", 6),
                ("2）", "当 CPU 访问主存地址 104184H 时，请说明该主存地址映射到 Cache 的哪一组，并写出计算过程。", 3),
            ],
        ),
        question(
            qid="instruction-1",
            section_id="instruction",
            number="三、1",
            title="8 位模型机指令格式与程序执行",
            score=12,
            stem="某 8 位模型计算机指令格式：OP（4 位）、MOD（2 位）、RD（2 位），第二字为 ADDR/DATA/DISP。除 HALT 为单字指令外，其他指令均为双字指令。表中给出 MOV/ADD/SUB/AND/SBB/JMP/HALT 操作码，MOD=立即、直接、变址、间接，RD=R0-R3。内存地址 30H-3BH 的部分内容见原卷表 2。",
            prompts=[
                ("①", "指令 SUB R3,((80H)) 的功能为 R3=((80H))-R3；使用间接寻址，请写出该指令机器码第一字节和第二字节。", 2),
                ("②", "若 PC=34H、变址寄存器 SI=20H，启动程序执行。请填写程序执行前三条指令的助记符、源操作数寻址方式、源操作数和执行结果。", 10),
            ],
        ),
        question(
            qid="instruction-2",
            section_id="instruction",
            number="三、2",
            title="扩展操作码编码设计",
            score=8,
            stem="某机器指令长 16 位，基本操作码 4 位，每个操作数地址码长 4 位，采用扩展码技术。要求设计一个指令系统：三地址指令 14 条，两地址指令 30 条，单地址指令 20 条，零地址指令 15 条。",
            prompts=[("作答", "请给出指令编码示意图。", 8)],
        ),
        question(
            qid="control-1",
            section_id="control",
            number="四、1",
            title="模型机指令功能与寻址方式",
            score=6,
            stem="某 8 位模型机系统结构如原卷图 1。图中控制信号均为高电平有效，MAR 中地址直接送地址总线 AB，变址寄存器 SI 隐含为 R3。某条指令的执行流程如原卷图 2。",
            prompts=[("作答", "写出图 2 所示指令的功能和操作数寻址方式。", 6)],
        ),
        question(
            qid="control-2",
            section_id="control",
            number="四、2",
            title="微指令控制信号与微指令格式",
            score=14,
            stem="基于同一 8 位模型机结构，分析图 2 指令执行流程和微程序控制器参数。",
            prompts=[
                ("1）", "写出图 2 中标注 ①、②、③ 的 3 条微指令必须发送的微操作控制信号。", 8),
                ("2）", "若控存容量为 256×32 位，控制字段对应 21 个控制信号，判别测试字段对应 5 个条件且采用编译法，后继微指令地址采用下址字段法，请设计水平型微指令格式。", 6),
            ],
        ),
        question(
            qid="io-1",
            section_id="system",
            number="五",
            title="DMA 与中断过程",
            score=5,
            stem="I/O 系统。",
            prompts=[
                ("1）", "在主机与外设交换信息的方式中，DMA 的中文名称是什么？", 1),
                ("2）", "请写出中断过程的四个阶段。", 4),
            ],
        ),
        question(
            qid="model-arm",
            section_id="model",
            number="六、1",
            title="ARM 模型机设计（选做）",
            score=17,
            stem="某 ARM 指令在原卷图 4 所示 ARM 模型机上执行过程见图 3：条件取指；Reg[rn]→A，Reg[rm]→B，Reg[rs]→C；Second_opr=对 B 移动 imm5 位；A+Second_opr→F；S=0 时不修改标志位；F→Reg[rd]。",
            prompts=[
                ("1）", "这条指令的功能是什么？", 2),
                ("2）", "该指令的操作数采用什么寻址方式？", 1),
                ("3）", "这是一条什么类型的指令？", 1),
                ("4）", "参考图 4 写出该指令在每个 clk 周期的控制信号。", 6),
                ("5）", "参考图 3 指令执行过程，结合图 4，画出 BX r0 指令流程图。", 3),
                ("6）", "对比原卷图 4 和图 5，简要叙述 ARM CPU 按条件取指令的过程。", 4),
            ],
        ),
        question(
            qid="model-riscv",
            section_id="model",
            number="六、2",
            title="RISC-V 多周期模型机（选做）",
            score=17,
            stem="一个能实现 RV32I 指令子集的多周期 RISC-V 模型机，结构如原卷图 4。",
            prompts=[
                ("1）", "根据给定执行过程 M0~M3，写出指令功能、助记符、指令格式和寻址方式。", 6),
                ("2）", "写出 M0 机器周期发送的控制信号。", 4),
                ("3）", "分析 ori rd,rs1,imm 和 sw rs2,imm(rs1) 的格式与执行过程，按机器周期填写操作。", 8),
                ("4）", "分析 jal、jalr、beq、bne 功能，至少说出三种实现无条件跳转的方法。", 3),
            ],
        ),
    ],
    2021: [
        question(
            qid="analysis-1",
            section_id="analysis",
            number="一、1",
            title="C 比较函数、端序与标志位",
            score=8,
            stem="假设某 32 位宿主机上，用 C 语言函数 LessThan(int X,int Y) 实现两个数据比较：若 X<Y 返回 -1，否则返回 0。调用时 int w; int A=0x12345678; int B=0x87654321; w=LessThan(A,B)。",
            prompts=[
                ("①", "w 的值是多少？若 X、Y、A、B 被定义为 unsigned 类型，则 w 又是多少？", 2),
                ("②", "若 p=&A，p 的值是 100；内存按字节编址、小端模式存放多字节数据，则内存 100 号单元内容是什么？", 2),
                ("③", "计算机对 X>Y 的比较通过 X-Y 实现。请写出 A-B 的运算结果以及 CF、OF、ZF、SF 的值，列出计算过程。", 4),
            ],
        ),
        question(
            qid="analysis-2",
            section_id="analysis",
            number="一、2",
            title="BF16 浮点数表示",
            score=4,
            stem="BF16 是深度学习中应用的一种 16 位浮点数格式，它直接将 IEEE 754 的 32 位浮点数尾数小数截尾为 7 位：数符 1 位，阶码 8 位（127 的移码），尾数 7 位（原码表示、隐藏尾数整数位 1）。",
            prompts=[("作答", "请写出 -5 的 BF16 浮点数。", 4)],
        ),
        question(
            qid="analysis-3",
            section_id="analysis",
            number="一、3",
            title="浮点数加减运算步骤",
            score=6,
            stem="给出浮点数的加减运算步骤，并以下面两个浮点数 X 和 Y（阶码和尾数均为 5 位）为例展示 X+Y 的运算过程：\nX=-0.1011×2^+0001，Y=0.1110×2^-0001。",
            prompts=[("作答", "写出 X+Y 的完整运算过程。", 6)],
        ),
        question(
            qid="memory-1",
            section_id="memory",
            number="二",
            title="16 位模型机主存、Cache 与 SRAM 设计",
            score=23,
            stem="某 16 位模型计算机按字编址，地址空间 64K。",
            prompts=[
                ("1）", "CPU 的地址位数有多少位？主存容量最大为多少字节？", 2),
                ("2）", "若有 1KB Cache，行大小 16B，2 路组相联，写出 CPU 访问主存时地址划分的高位标记、Cache 组地址、块内地址位数。", 3),
                ("3）", "设 Cache 初始为空，请描述 CPU 访问 2021H 单元后 Cache 发生了什么变化。", 3),
                ("4）", "用 8K×8 位 SRAM 芯片构成 32K×16 位主存物理空间，需要多少片芯片？", 1),
                ("5）", "假设 I/O 和主存统一编址，前 32K 为主存空间，后 32K 为 I/O 空间，画出 CPU 与主存连接图，标注地址和数据信号。", 8),
                ("6）", "说明你设计的主存是顺序编址还是交叉编址，并说明如何变成另一种编址方式。", 3),
                ("7）", "判断题：SRAM 常用于构成内存条；速度最快的非易失性存储器是 SRAM；虚拟存储器由存储器管理硬件和操作系统共同管理实现。", 3),
            ],
        ),
        question(
            qid="instruction-1",
            section_id="instruction",
            number="三",
            title="16 位计算机 X 指令系统与程序功能",
            score=18,
            stem="16 位计算机 X 的指令字长有单字和双字两种。单字格式：OP(7)、DR(3)、SR1(3)、SR2(3)；双字格式：OP(5)、MOD(2)、DR(3)、SR1(3)、SR2(3)，第二字为 Imme/Addr/Offset。题中给出从 4000H 开始的一段程序与机器码/数据表。",
            prompts=[
                ("1）", "该计算机有多少个寄存器？若双字指令有 20 条，单字指令最多有多少条？", 3),
                ("2）", "选择该计算机存储器的编址方式：按字节、按字、按双字或无法判断。", 2),
                ("3）", "仿照序号 1 指令，翻译序号 2 指令并写出汇编助记符。", 2),
                ("4）", "分析 XOR R3,R0,[R2] 中 [R2] 的寻址方式、执行后 R3 内容；若 XOR 操作码为全零，写出其指令码。", 5),
                ("5）", "写出 JNZ L 的指令码。JNZ 的 OP 为 (11100)2，采用相对寻址（MOD=11）。", 3),
                ("6）", "描述这段程序的功能。", 3),
            ],
        ),
        question(
            qid="control-1",
            section_id="control",
            number="四",
            title="模型计算机 X 控制器设计",
            score=16,
            stem="16 位模型计算机 X 的系统结构如原卷图 1，指令系统格式如第三题。取指周期 M0：MEM[PC]→IR，PC+1→PC，IDC。指令系统有 MOV DR,Imme 和 JMP offset 两条指令。",
            prompts=[
                ("1）", "请按照机器周期顺序写出 MOV 和 JMP 指令的执行过程。", 8),
                ("2）", "选择一个机器周期操作，写出它发送的微操作控制信号。", 3),
                ("3）", "若采用微程序控制器，控存 1K 单元；控制字段直接控制，微程序转移方式 3 种且采用译码方式；下址字段可在整个控存转移。求控制字段、转移控制字段、下址字段位数和控存容量。", 5),
            ],
        ),
        question(
            qid="io-1",
            section_id="system",
            number="五",
            title="I/O 端口地址与中断隐指令",
            score=4,
            stem="I/O 系统。",
            prompts=[
                ("1）", "接第二题第 5 小题，请写出一个 I/O 设备端口地址，并写出另一种 I/O 端口地址编址方式。", 2),
                ("2）", "中断隐指令是在中断的哪个阶段、由谁执行？（A.中断响应、硬件 B.中断请求、OS C.中断处理、软件 D.中断返回、硬件及 OS）", 2),
            ],
        ),
        question(
            qid="model-arm",
            section_id="model",
            number="六、1",
            title="ARMv8 极简 CPU 设计（选做）",
            score=21,
            stem="程序片段：L1: SUBIS r4,r1,ALU_imm；BL L1。需要设计一个 RISC 结构 ARMv8 CPU，支持仅包含 I 型 SUBIS 和 B 型 BL 的指令系统。机器字长、寄存器宽度均为 32 位，存储器按字节编址。",
            prompts=[
                ("1）", "画出 CPU 结构图并标出控制信号。", 13),
                ("2）", "画出该指令系统对应的微程序流程图和各状态发出的有效控制信号。", 8),
            ],
        ),
        question(
            qid="model-riscv",
            section_id="model",
            number="六、2",
            title="RV32I 多周期 RISC-V 模型机（选做）",
            score=21,
            stem="一个能实现 RV32I 指令集的多周期 RISC-V 模型机，结构如原卷图 2。",
            prompts=[
                ("作答", "根据原卷给出的 RISC-V 模型机结构和题目要求完成设计与分析。涉及图形部分请结合原卷备用 PDF。", 21),
            ],
        ),
    ],
}


def extend_data() -> None:
    DATA[2019] = [
        question(
            qid="part1-1",
            section_id="part1",
            number="一、1",
            title="CPU 与 SRAM 存储器系统连接",
            score=10,
            stem="CPU 字长 16 位，地址线 A0~A15，数据线 D0~D15。存储器系统由 2 片 8K×16bit 和 1 片 16K×16bit SRAM 组成，从地址 2000H 开始占有连续 32KB 空间，按字编址。原卷给出 CPU 与存储器的不完整连接图及控制信号逻辑功能表。",
            prompts=[("作答", "按照给出条件添加逻辑电路，在图 1 上完成 CPU 与存储器系统连接，并标出信号线和地址线连接。", 10)],
        ),
        question(
            qid="part1-2",
            section_id="part1",
            number="一、2",
            title="64KW 存储系统带宽提升",
            score=8,
            stem="采用 8K×16bit SRAM 组成 64KW 存储系统，存储器读写时间是总线传送时间的 8 倍，要求提高存储器带宽。",
            prompts=[
                ("1）", "可采用什么方式组织存储器？", 2),
                ("2）", "写出存储器组织的地址格式并标出各字段含义和位数。", 4),
                ("3）", "该机器属于 SISD、SIMD、MISD、MIMD 中的哪种结构？", 2),
            ],
        ),
        question(
            qid="part1-3",
            section_id="part1",
            number="一、3",
            title="自定义浮点数编码与 X+Y",
            score=20,
            stem="该机支持浮点数格式：数符 1 位、尾数 11 位、阶符 1 位、阶码 3 位；阶码用移码表示，尾数用补码表示。设 X=13/64，并给出 [X]浮、[Y]浮 的编码用于计算 [X+Y]浮。",
            prompts=[
                ("1）", "求 X 的二进制规格化真值。", 2),
                ("2）", "将 [X]浮 的编码按给定格式填入空格。", 2),
                ("3）", "若采用小端格式存储，写出该浮点数从内存地址 N 开始存储的 16 进制数值。", 2),
                ("4）", "写出浮点数加减运算除零操作数检查外的 4 个步骤。", 4),
                ("5）", "根据给定 [X]浮 和 [Y]浮，求 [X+Y]浮，写出对阶、尾数运算、规格化、舍入等步骤。", 10),
            ],
        ),
        question(
            qid="part2-1",
            section_id="part2",
            number="二、1",
            title="64KW 主存与 1KW Cache 地址格式",
            score=6,
            stem="主存容量 64KW，Cache 容量 1KW，2 路组相联，每块 2 个字，字长 16bit。",
            prompts=[("作答", "画出主存地址格式，并标出每个字段的含义和位数。", 6)],
        ),
        question(
            qid="part2-2",
            section_id="part2",
            number="二、2",
            title="Cache 组号计算",
            score=2,
            stem="在第二大题 Cache 条件下。",
            prompts=[("作答", "主存地址 2300H 可映射到 Cache 的哪一组？", 2)],
        ),
        question(
            qid="part2-3",
            section_id="part2",
            number="二、3",
            title="RISC 指令格式设计",
            score=10,
            stem="机器采用 RISC 指令系统，共有 8 个 16 位寄存器，指令字长固定为双字长；最多定义 128 种操作，具有立即、直接、间接、寄存器、寄存器间接、变址、相对、堆栈等 8 种寻址方式；指令包括 R-R、R-S、S-R 三种类型。",
            prompts=[("作答", "设计该机指令格式，并说明各字段功能与位数。", 10)],
        ),
        question(
            qid="part2-4",
            section_id="part2",
            number="二、4",
            title="哈佛结构指令 Cache 程序分析",
            score=16,
            stem="改为哈佛结构，在指令存储器设置容量 1KW 的 Cache，2 路组相联，每块 2 个字。按题 3 指令格式，给出一段 C 程序及汇编程序，从 L0 到 L2（不包括 L2）执行。",
            prompts=[
                ("1）", "将标号 L1 开始的 4 条指令的源操作数寻址方式填入表 3。", 4),
                ("2）", "分析执行该指令段的指令 Cache 命中率 h。", 4),
                ("3）", "若指令存储器访问 10ns、Cache 访问 2ns，求平均访问时间 ta。", 2),
                ("4）", "求 Cache 效率 e。", 2),
                ("5）", "若指令地址 L0 从 2100H 开始，求 L1 所在指令地址。", 2),
                ("6）", "求指令 JNE L1 的偏移地址，要求用补码表示并写出计算公式。", 2),
            ],
        ),
        question(
            qid="part3-1",
            section_id="part3",
            number="三、1",
            title="微指令格式设计",
            score=6,
            stem="模型机字长 8 位，地址总线 8 位，采用微程序控制器。共有指令 100 条，每条平均需 7 条微指令实现，其中 3 条共用；微操作直接控制，下条地址由下址字段给出，J1~J3 采用译码输出。",
            prompts=[("作答", "设计微指令格式，并说明各字段位数和含义。", 6)],
        ),
        question(
            qid="part3-2",
            section_id="part3",
            number="三、2",
            title="ADD R0,10H 微程序流程补全",
            score=6,
            stem="图 3 是实现 ADD R0,10H 的微程序流程图，缺少三条微指令。指令功能：[R0]+10H→R0，2 字节指令，第二字节为 10H。",
            prompts=[("作答", "填入合适微指令完成流程图，并说明 PC→AR、PC+1→PC 微指令产生的微命令信号。", 6)],
        ),
        question(
            qid="part4-1",
            section_id="part4",
            number="四",
            title="MIPS 单周期 CPU 与 lw 指令",
            score=16,
            stem="图 4 是实现 32 位 MIPS 单周期模型机结构和数据通路。ALU 支持 ADD、SUB、SLL、AND。指令 lw rt,(rs+imm) 为访存取数：[(rs)+imm]→rt。",
            prompts=[
                ("1）", "在图 4 上画出 lw 指令从取指到完成执行的数据通路。", 6),
                ("2）", "指出该机器采用哈佛结构还是普林斯顿结构，并说明它和冯·诺依曼结构的不同。", 2),
                ("3）", "写出 lw 指令的数据通路对应控制信号取值。", 3),
                ("4）", "若指令在时钟上沿开始执行，PC_NEW 应在上沿还是下沿送入 PC？", 2),
                ("5）", "虚拟存储器中，虚拟地址到物理地址的变换有哪三种方式？", 3),
            ],
        ),
    ]

    DATA[2020] = [
        question(
            qid="part1-1",
            section_id="part1",
            number="一、1",
            title="8 位模型机控制器与微指令",
            score=10,
            stem="图 1 是某 8 位模型机结构框图，IR、PC、MEM、AR、R0-R3、ALU 等部件及控制信号已给出。图 2 给出某指令执行流程。",
            prompts=[
                ("1）", "图 1 中哪些部件属于控制器部分？", 3),
                ("2）", "若微指令由控制字段、判别测试字段和下址字段组成，控制字段直接控制，判别测试字段直接编译，控存 256 个地址单元，求微指令长度和下址字段位数。", 3),
                ("3）", "图 2 中的指令是什么指令？采用什么寻址方式？", 2),
                ("4）", "写出图 2 中标注 ①、② 的微指令必须发送的微操作控制信号。", 2),
            ],
        ),
        question(
            qid="part1-2",
            section_id="part1",
            number="一、2",
            title="16 位浮点格式与 X+Y",
            score=11,
            stem="模型机另有 16 位浮点运算部件。浮点格式：数符 1 位、尾数 7 位、阶符 1 位、阶码 7 位；阶码用移码，尾数用补码。已知 X=7/32，Y 的浮点数表示为 A87FH。",
            prompts=[
                ("1）", "规格化数表示尾数有什么优点？", 2),
                ("2）", "写出 X 的规格化浮点数表示形式。", 2),
                ("3）", "求 Y 的二进制真值。", 2),
                ("4）", "求 X+Y 浮点数 [X+Y]浮，采用 0 舍 1 入法，列出计算步骤。", 5),
            ],
        ),
        choice_group(
            "part1-3",
            "part1",
            "一、3-4",
            "体系结构与中断方式选择",
            4,
            [
                ("3）", "从图 1 可以看出，该计算机采用的体系结构是（ ）。", [("A", "哈佛结构"), ("B", "冯·诺依曼结构"), ("C", "ARM 结构"), ("D", "MIPS 结构")]),
                ("4）", "CPU 采用程序中断方式与外设交换数据，下面说法错误的是（ ）。", [("A", "实时性强"), ("B", "CPU 与外设可并行工作"), ("C", "中断发生的时间可预知"), ("D", "支持中断控制的硬件相对复杂")]),
            ],
        ),
        question(
            qid="part1-5",
            section_id="part1",
            number="一、5",
            title="扩展操作码指令格式",
            score=6,
            stem="指令长度为两个字节，每个操作数长度为 5 bit，采用指令操作码扩展技术，要求编写 62 条双操作数指令、63 条单操作数指令和 30 条无操作数指令。",
            prompts=[
                ("1）", "画出双操作数、单操作数和无操作数指令格式。", 3),
                ("2）", "写出三类指令所占编码范围。", 3),
            ],
        ),
        question(
            qid="part1-6",
            section_id="part1",
            number="一、6",
            title="Cache/主存平均访问时间",
            score=10,
            stem="CPU 与主存之间添加 Cache，Cache 中缺失数据总能在主存中找到。Cache 访问时间 5ns，局部命中率 97%；主存访问时间 60ns。",
            prompts=[
                ("1）", "CPU 访问 Cache/主存存储体系的平均访问时间是多少？", 3),
                ("2）", "若 Cache 和主存采用组相联映射，画出主存地址字段及名称。", 3),
                ("3）", "可以从哪些技术方面改进以缩短平均访问时间？", 4),
            ],
        ),
        question(
            qid="part1-7",
            section_id="part1",
            number="一、7",
            title="双字指令格式与程序执行",
            score=14,
            stem="模型机支持双字指令：OP(4)、MOD(2)、DR(2)，第二字为地址/数据/偏移量/端口号。除 HALT 和 DEC 为单字指令外，其他均为双字指令。给出 MOV/SUB/DEC/IN/ADD/JMP/HALT 编码、寻址方式、寄存器编码及内存表。程序从 L0 开始，PC=20H，SI=11H。",
            prompts=[
                ("1）", "填写程序执行前三条指令的助记符、寻址方式、源操作数、执行结果、R1 和 FR。", 10),
                ("2）", "写出 DEC R3 的机器码。", 2),
                ("3）", "写出 JMP L1 第一个字地址和相对跳转 8 位补码偏移量。", 2),
            ],
        ),
        question(
            qid="part2-1",
            section_id="part2",
            number="二、1",
            title="MIPS addi 数据通路与控制信号故障",
            score=12,
            stem="图 3 是 32 位 MIPS 单周期模型机结构和数据通路。分析指令 addi rt,rs,imm（rs+符号扩展 imm→rt）。",
            prompts=[
                ("1）", "如果 imm_s 信号恒为 0，该指令能否正常运行？为什么？", 6),
                ("2）", "若所有控制信号正常，描述该指令执行过程中除控制信号外经过的所有部件数据通路。", 6),
            ],
        ),
        question(
            qid="part2-2",
            section_id="part2",
            number="二、2",
            title="int/short 类型转换",
            score=7,
            stem="在该系统中，变量 i=65533，sizeof(int)=4，sizeof(short)=2。执行：int i=65533; short j=(short)i; int k=j;",
            prompts=[("作答", "分析变量 i、j、k 的真值，并写出详细分析过程。", 7)],
        ),
        question(
            qid="part2-3",
            section_id="part2",
            number="二、3",
            title="MIPS 循环程序机器码分析",
            score=15,
            stem="高级语言循环：while(Binary[count] == Dest_Char) count += 1; 编译为 MIPS 代码，原卷给出从 loop 开始的机器码表和寄存器编号表。",
            prompts=[
                ("1）", "该程序中哪些是 R 型指令？哪些是 I 型指令？", 5),
                ("2.1）", "写出寄存器 reg_3 和 reg_4 对应的寄存器名称，并说明理由。", 4),
                ("2.2）", "编号 exit 的值是多少？", 2),
                ("2.3）", "该 MIPS 模型机的编址单位是什么？每个数组元素 Binary[i] 占几个字节？", 4),
            ],
        ),
        question(
            qid="part2-4",
            section_id="part2",
            number="二、4",
            title="DRAM 数据存储器设计",
            score=11,
            stem="模型机数据存储器采用 DRAM，容量 64K×16 位，由 16K×4 位 DRAM 芯片（内部 256×256）构成，存储器读/写周期 500ns。",
            prompts=[
                ("1）", "该数据存储器存储位元共有多少个？", 2),
                ("2）", "若 DRAM 采用异步刷新方式，单元刷新间隔不超过 2ms，则刷新信号周期是多少？存储器刷新一遍最少用多少时间？", 4),
                ("3）", "需要多少个 DRAM 芯片？简述扩展方式，并写出每组 16K×16 位存储区域的地址范围。", 5),
            ],
        ),
    ]

    DATA[2018] = [
        question(
            qid="part1-1",
            section_id="part1",
            number="一、1",
            title="浮点数规格化与 X-Y",
            score=12,
            stem="某 8 位模型机另有浮点运算部件。浮点格式：数符 1 位、阶符 1 位、阶码 7 位、尾数 7 位；阶码用移码，尾数用补码。已知 X=15/64，Y 的规格化浮点表示为 C2BBH。",
            prompts=[
                ("1）", "使用规格化浮点数表示数据有什么优点？", 3),
                ("2）", "写出 X 的规格化浮点数表示形式。", 2),
                ("3）", "求 Y 的二进制真值。", 2),
                ("4）", "求 X-Y 浮点数 [X-Y]浮（采用 0 舍 1 入法，列出计算步骤）。", 5),
            ],
        ),
        question(
            qid="part1-2",
            section_id="part1",
            number="一、2",
            title="补码加减法器设计",
            score=6,
            stem="使用二进制并行加法器和其他组合逻辑电路，设计一个补码加减法器。",
            prompts=[("作答", "画出逻辑框图（简图），说明信号功能和工作原理。", 6)],
        ),
        question(
            qid="part1-3",
            section_id="part1",
            number="一、3",
            title="双字指令程序执行分析",
            score=14,
            stem="模型机双字指令格式：OP(4)、MOD(2)、RD(2)，第二字为地址/数据/偏移量/端口号；单字指令为第一字。除 HALT 和 INC 为单字指令外，其他为双字指令。给出 MOV/SUB/INC/IN/ADD/JMP/HALT 编码、MOD、RD 表和内存表。",
            prompts=[
                ("1）", "若 PC=20H，SI=10H，从 L0 开始执行，请填写前三条指令的助记符、寻址方式、源操作数、执行结果、R1 和 FR。", 10),
                ("2）", "写出 INC R2 的机器码。", 2),
                ("3）", "写出 JMP L1 第一个字地址，以及相对寻址的 8 位偏移量。", 2),
            ],
        ),
        question(
            qid="part1-4",
            section_id="part1",
            number="一、4",
            title="微程序控制器与指令流程",
            score=12,
            stem="模型机采用微程序控制器。图 2 给出某条指令执行流程：PC→MAR,PC+1；MEM→IR,IDC；PC→MAR,PC+1；MEM→LA；DR→LB；LA⊕LB→DR。",
            prompts=[
                ("1）", "写出该条指令的功能和操作数寻址方式。", 4),
                ("2）", "写出图 2 中标注 ①、②、③ 的 3 条微指令必须发送的微操作控制信号。", 4),
                ("3）", "若控制字段直接控制，下址字段 8 位，微程序分支条件 3 种且采用直接编译法，设计微指令格式并计算控制存储器容量。", 4),
            ],
        ),
        question(
            qid="part1-5",
            section_id="part1",
            number="一、5",
            title="主存地址划分与 Cache 组成",
            score=10,
            stem="模型机升级后主存容量 1MB，按字节编址；Cache 容量 8KB，每块 8B，4 路组相联。",
            prompts=[
                ("1）", "写出访问 Cache 时主存地址格式划分。主存地址 48FBDH 映射到 Cache 哪一组？", 4),
                ("2）", "比较 DRAM 和 SRAM，并结合 Cache 特点说明为什么 Cache 一般采用 SRAM 构成。", 6),
            ],
        ),
        question(
            qid="part1-6",
            section_id="part1",
            number="一、6",
            title="DRAM 刷新周期",
            score=4,
            stem="数据存储器容量扩展为 1M×8 位，由 128 个 64K×1 位 DRAM 芯片（芯片内 4 个 128×128 结构）构成，读/写周期 100ns，刷新间隔 2ms。",
            prompts=[("作答", "采用集中刷新方式的刷新周期是多少？采用异步刷新方式的刷新信号周期是多少？", 4)],
        ),
        question(
            qid="part2-7",
            section_id="part2",
            number="二、7",
            title="IEEE754 与定点移位",
            score=6,
            stem="MIPS 单周期模型机相关。IEEE754 单精度浮点数阶码 8 位，127 移码；尾数 24 位，原码表示，含隐藏位。",
            prompts=[
                ("1）", "若 32 位浮点寄存器 FR1 中 X=-0.25，写出 FR1 内容（16 进制）。", 2),
                ("2）", "FR2=C30FC000H，若它是 IEEE754 单精度浮点数，求十进制真值；若是补码定点小数，写出算术右移 1 位和算术左移 1 位后的 16 进制编码。", 4),
            ],
        ),
        question(
            qid="part2-8",
            section_id="part2",
            number="二、8",
            title="哈佛结构与冯·诺依曼结构",
            score=3,
            stem="MIPS 模型机使用两个存储器。",
            prompts=[("作答", "说明该模型机为何使用两个存储器，写出结构名称，并说明它和冯·诺依曼体系结构的不同。", 3)],
        ),
        question(
            qid="part2-9",
            section_id="part2",
            number="二、9",
            title="微程序控制与硬布线控制",
            score=5,
            stem="图 1 使用微程序控制器，图 3 使用硬布线控制。",
            prompts=[("作答", "两种控制器如何划分？各自优点是什么？", 5)],
        ),
        question(
            qid="part2-10",
            section_id="part2",
            number="二、10",
            title="sll 指令执行能力分析",
            score=5,
            stem="分析图 3 所示 MIPS 模型机结构能否实现 sll 指令：sll rd,rt,shamt；逻辑左移 (rt << shamt) → rd。",
            prompts=[("作答", "如能实现，描述执行过程；如不能，需要添加什么部件或功能？", 5)],
        ),
        question(
            qid="part2-11",
            section_id="part2",
            number="二、11",
            title="MIPS 循环程序与控制信号",
            score=11,
            stem="给定 while(A[i] == k) i+=1; 对应的 MIPS 汇编程序和表 5 机器代码。寄存器 $s0、$s1、$t0、$t1、$t3 等用于变量和数组地址。",
            prompts=[
                ("1）", "根据表 5，求 rs、rt、offset、address，并判断数组 A 中每个元素位数。", 5),
                ("2）", "写出表 6 中各指令的数据通路对应控制信号。无关信号填“-”。", 6),
            ],
        ),
        question(
            qid="part2-12",
            section_id="part2",
            number="二、12",
            title="最高端数据存储器 SRAM 扩展",
            score=12,
            stem="MIPS 单周期 CPU 外接数据存储器，容量 32M×32 位，位于存储器空间最高端。CPU 地址线 32 位、数据线 32 位；控制信号 MREQ# 低有效，Mem_Write 高电平写。用 8M×16 位 SRAM 构成。",
            prompts=[
                ("1）", "写出数据存储器地址范围。", 2),
                ("2）", "分析各组 SRAM 芯片的地址范围。", 4),
                ("3）", "设计地址译码电路，并画出 CPU 与所选芯片连接图，SRAM 片内 WE 低电平写有效。", 6),
            ],
        ),
    ]

    DATA[2017] = [
        question(
            qid="part1-1",
            section_id="part1",
            number="一、1",
            title="16 位补码浮点数与尾数加法微程序",
            score=12,
            stem="图 1 是某单总线结构计算机。浮点数格式：阶码 8 位（含符号位）、尾数 8 位（含符号位），阶码和尾数均用补码表示，排列为阶符、阶码、数符、尾数。已知 X=-17.25，Y 的规格化浮点表示为 FE78H。",
            prompts=[
                ("1）", "写出 X 的规格化浮点数表示形式。", 2),
                ("2）", "求 Y 的二进制真值。", 2),
                ("3）", "求 [X+Y]补，要求用补码计算，采用 0 舍 1 入法，列出计算步骤。", 5),
                ("4）", "若用图 1 ALU 和相关部件完成浮点加法尾数运算，尾数在 R0/R1，和存入 R0，请用微程序流程图描述过程。", 3),
            ],
        ),
        question(
            qid="part1-2",
            section_id="part1",
            number="一、2",
            title="相对跳转程序地址",
            score=5,
            stem="一段程序在图 1 模型机上运行，所有指令均为 2 字节，存储器按字节编址，程序装入内存低端，起始地址为 0。程序含 MOV、IN、ADD、OUT、JMP L 等指令，L 为标号。",
            prompts=[("作答", "求最后一条 JMP L 的存放地址，以及相对寻址的 8 位二进制偏移量。", 5)],
        ),
        question(
            qid="part1-3",
            section_id="part1",
            number="一、3",
            title="机器指令格式与执行跟踪",
            score=11,
            stem="模型机支持指令格式：Opcode(4)、Rd(2)、MOD(2)，第二字节 Addr/Disp/Data。除 INC 和 HALT 为 1 字节外，其他为 2 字节。给出 ADD/SUB/ADC/SBB/MOV/INC/JMP/HALT 编码、寻址方式、寄存器编码以及内存表。PC=20H，SI=10H。",
            prompts=[
                ("1）", "指令 ADD R1,[10H] 功能为 (R1)+Mem[10H]→R1，请写出机器代码。", 4),
                ("2）", "启动程序执行后，程序执行了几条指令停止？写出前 2 条指令的助记符、寻址方式、EA、操作数和执行结果。", 7),
            ],
        ),
        question(
            qid="part1-4",
            section_id="part1",
            number="一、4",
            title="微指令字段与控存容量",
            score=4,
            stem="该机采用微程序控制器，共 28 种微操作命令，其中 14 个微命令采用译码方式，其余直接控制；7 个转移控制状态采用译码形式；下址字段 7 位。",
            prompts=[("作答", "求操作控制字段和判别测试字段各有几位，并给出控存容量（字数×字长）。", 4)],
        ),
        question(
            qid="part1-5",
            section_id="part1",
            number="一、5",
            title="控制器组成与功能",
            score=5,
            stem="结合图 1 所示模型机实例。",
            prompts=[("作答", "说明控制器由哪些部件组成，各部件主要功能是什么。", 5)],
        ),
        question(
            qid="part1-6",
            section_id="part1",
            number="一、6",
            title="Cache 命中率与地址划分",
            score=6,
            stem="模型机扩展主存并添加 Cache。Cache 完成存取 1700 次，主存完成 300 次；Cache 周期 10ns，主存周期 70ns。升级后主存容量 64KB，按字节编址；Cache 容量 4KB，每块 4 字节，4 路组相联。",
            prompts=[("作答", "求 Cache 命中率、平均访问时间、主存字节地址位数、标记位数、Cache 组地址位数，以及主存地址 07A8H 映射到哪一组。", 6)],
        ),
        question(
            qid="part1-7",
            section_id="part1",
            number="一、7",
            title="4 体交叉存储器访存时间",
            score=4,
            stem="主存容量 32 字，字长 64 位，存储周期 200ns，数据总线宽度 64 位，总线传送周期 50ns。采用 4 体交叉方式连续读出 21 个字且无阻塞。",
            prompts=[("作答", "求访存时间，以及相比不采用交叉方式节省的时间。", 4)],
        ),
        question(
            qid="part1-8",
            section_id="part1",
            number="一、8",
            title="汉字文本与字模码容量",
            score=4,
            stem="输出设备是一台打印机，采用 32×32 点阵汉字字形。需要打印 50 个汉字构成的短文。",
            prompts=[("作答", "求短文纯文本占用内存字节数；若 50 个字不重复，打印所用字模码共多少字节。", 4)],
        ),
        question(
            qid="part2-9",
            section_id="part2",
            number="二、9",
            title="MIPS 程序控制信号",
            score=10,
            stem="图 2 是 MIPS 单周期 CPU。给定程序将主存地址 10H 起始的 20 个字累加，含 add、addi、lw、beq、j、sw 等指令。",
            prompts=[("作答", "填写表 1 中指定 5 条指令（5、7、8、9、10）所发出的控制信号；无关信号填“-”。", 10)],
        ),
        question(
            qid="part2-10",
            section_id="part2",
            number="二、10",
            title="独立编址 I/O 指令格式",
            score=4,
            stem="为实现独立编址输入输出，使用 I 型指令格式实现 in 和 out，端口地址由指令低 16 位 I15-0 提供，控制信号为 IO_R 和 IO_W。",
            prompts=[("作答", "仿照 xori 指令写法，分别写出 in 和 out 指令格式和功能描述。", 4)],
        ),
        question(
            qid="part2-11",
            section_id="part2",
            number="二、11",
            title="IN/OUT 指令控制信号",
            score=6,
            stem="ALU 有 16 种功能。为实现 IN 和 OUT 指令的数据通路，译码与控制单元需设置对应控制信号。",
            prompts=[("作答", "将 in 和 out 指令的 w_r_s、imm_s、rt_imm_s、wr_data_s、ALU_OP、Write_Reg、Mem_Write、IO_R、IO_W、PC_s 填入表 3。", 6)],
        ),
        question(
            qid="part2-12",
            section_id="part2",
            number="二、12",
            title="MIPS CPU 与冯·诺依曼结构比较",
            score=6,
            stem="结合图 2 所示 MIPS CPU 结构。",
            prompts=[("作答", "说明它和冯·诺依曼体系结构有何不同，冯·诺依曼体系结构特点在其上有何体现。", 6)],
        ),
        question(
            qid="part2-13",
            section_id="part2",
            number="二、13",
            title="可变长度操作码分配原则",
            score=3,
            stem="若图 2 MIPS 机的指令操作码长度可变。",
            prompts=[("作答", "根据指令出现频度分配操作码长度的原则是什么？", 3)],
        ),
        question(
            qid="part2-14",
            section_id="part2",
            number="二、14",
            title="DRAM 存储原理与特性",
            score=6,
            stem="图 2 数据存储器采用 DRAM 构成。",
            prompts=[("作答", "说明 DRAM 利用什么存储电荷表示 0/1；为什么需要刷新；相比 SRAM，DRAM 的速度和价格如何。", 6)],
        ),
        question(
            qid="part2-15",
            section_id="part2",
            number="二、15",
            title="DRAM 集中刷新时间",
            score=2,
            stem="数据存储器容量扩展为 64K×16 位，由 16K×1 位 DRAM 芯片（内部 128×128）构成，读/写周期 50ns，采用集中式刷新。",
            prompts=[("作答", "求存储器刷新一遍最少用时。", 2)],
        ),
        question(
            qid="part2-16",
            section_id="part2",
            number="二、16",
            title="64M×32 位数据存储器 SRAM 扩展",
            score=12,
            stem="MIPS 系统数据存储器容量为 64M×32 位，位于存储器空间最低端；若由 16M×8 位 SRAM 构成。",
            prompts=[
                ("1）", "写出数据存储器地址范围。", 2),
                ("2）", "求所需 SRAM 芯片个数。", 2),
                ("3）", "画出 SRAM 芯片扩展成数据存储器的连接图，清晰标示地址、数据和控制信号线。", 8),
            ],
        ),
    ]


def main() -> None:
    extend_data()
    STRUCTURED_DIR.mkdir(parents=True, exist_ok=True)
    for year, questions in DATA.items():
        target = STRUCTURED_DIR / f"{year}.json"
        target.write_text(
            json.dumps({"year": year, "questions": questions}, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
        print(f"wrote {target} ({len(questions)} questions)")


if __name__ == "__main__":
    main()
